### ISSUE TITLE
视频文件查询

### ISSUE THREAD

**Issue by Alanqiu** [zengcanxiang/AndroidQStorage#3]
![image](https://user-images.githubusercontent.com/5857925/121656951-9368e480-cad2-11eb-980b-53b7f02fa652.png)
你好，这个查询方法可以查询DCIM/sample目录下的图片和视频一起查询吗？我把视频和图片都保存到DCIM 下，想视频图片都能查询到，类似系统的媒体库那样子

**Comment by zengcanxiang** [comment]
这个方法只是对查询到的数据进行处理，转换为uri对象。

查询内容是由传入的queryUri决定的。

queryUri是系统的MediaAPI构建出来的。这个你可以看看系统的类里面有几种Media类型
